language: php
sudo: required
services:
- mysql
addons:
  chrome: stable
git:
  depth: 3
cache:
  directories:
  - $HOME/.composer/cache
php:
- 5.6
- 7.0
- 7.1
- 7.2
# - 7.3
matrix:
  fast_finish: true
jobs:
  include:
  - stage: deploy
    name: "Trigger build for external modules"
    install: skip
    script: .travis/trigger-modules.sh
    if: fork = false
install:
- .travis/install-dependencies.sh
- .travis/setup-humhub.sh
script:
- '$HOME/chromedriver --url-base=/wd/hub &'
- 'php --server 127.0.0.1:8080 --docroot ${TRAVIS_BUILD_DIR} &>/tmp/phpserver.log &'
- 'sleep 5 && curl --fail --head http://127.0.0.1:8080/index-test.php'
- 'cd protected/humhub/tests'
- 'php ../../vendor/bin/codecept build'
- 'php ../../vendor/bin/codecept run --env travis'
- 'cd ../../../'
after_failure:
- .travis/upload-failure.sh
env:
  global:
    secure: EGSE10Ya3jf7+CVwOo2L2iTySqpCKN64VpfeXKnmwy/gPzqfGq7p+Rjc5w7E0AGQgRCUmuw6QB+oyg32qlutW8ZzS7JHtnJTWOR8kkzrkpFohDVCFNOBofn4ckd1h64MWcLoF1otNa2GQAZBT/sgdE7HxmEnbCdqESZPEGQ/Q3I=
